### ISSUE TITLE
Forces install to /Applications/MiddleClick.app instead of ~/Applications/MiddleClick.app

### ISSUE THREAD

**Issue by kajukenbo** [artginzburg/MiddleClick-BigSur#14]
Not great on a shared machine or one that does not allow writing to /Applications

**Comment by DaFuqtor** [comment]
Any screenshots? I have an app instance working from the `~/Downloads` folder right now, no problems ¯\_(ツ)_/¯

**Comment by kajukenbo** [comment]
`
% brew cask reinstall middleclick --verbose
==> Downloading https://github.com/DaFuqtor/MiddleClick/releases/download/2.4.5/MiddleClick.zip
Already downloaded: /Users/zzzzzzz/Library/Caches/Homebrew/downloads/8b9d030ac4cb1df0944d499031a09b75a336c027449972a330d6417e02b6bd2c--MiddleClick.zip
==> Verifying SHA-256 checksum for Cask 'middleclick'.
==> Uninstalling Cask middleclick
==> Removing login item /Applications/MiddleClick.app
==> Removing login item MiddleClick
Warning: It seems there is already an App at '/Users/zzzzzzz/homebrew/Caskroom/middleclick/2.4.5/MiddleClick.app'; overwriting.
==> Removing App '/Users/zzzzzzz/homebrew/Caskroom/middleclick/2.4.5/MiddleClick.app'.
==> Purging files for version 2.4.5 of Cask middleclick
==> Installing Cask middleclick
unzip -o /Users/zzzzzzz/Library/Caches/Homebrew/downloads/8b9d030ac4cb1df0944d499031a09b75a336c027449972a330d6417e02b6bd2c--MiddleClick.zip -d /var/folders/17/g5sbky9d4f986csy6l6r6txw4xwq5f/T/d20191205-79895-4hiatk
cp -pR /var/folders/17/g5sbky9d4f986csy6l6r6txw4xwq5f/T/d20191205-79895-4hiatk/MiddleClick.app/. /Users/zzzzzzz/homebrew/Caskroom/middleclick/2.4.5/MiddleClick.app
chmod -Rf +w /var/folders/17/g5sbky9d4f986csy6l6r6txw4xwq5f/T/d20191205-79895-4hiatk
==> Moving App 'MiddleClick.app' to '/Applications/MiddleClick.app'.
Password:
`

**Comment by kajukenbo** [comment]
Should I move everything to `~/Downloads/homebrew` instead of `~/homebrew` ?

**Comment by DaFuqtor** [comment]
I mean, any folder is suitable for me, but I didn't know that you tried to do this via Homebrew.

**Comment by DaFuqtor** [comment]
I think this problem could be solved by reading some Homebrew manuals. In theory, they were supposed to give people the opportunity to change the installation location.

**Comment by kajukenbo** [comment]
FWIW, I followed the "Recommended" instructions from here:
https://github.com/DaFuqtor/MiddleClick-Catalina

**Install**
**Via 🍺 Homebrew Cask (Recommended)**
`brew cask install middleclick"`

Am I to take it to mean you don't really expect people to install it that way?

**Comment by DaFuqtor** [comment]
It's not about me, it's about Homebrew, ask them lol

**Comment by artginzburg** [comment]
This can be solved by choosing Direct Download over Homebrew. The app works from anywhere.
