### ISSUE TITLE
Support for Apple Silicon

### ISSUE THREAD

**Issue by jackblk** [artginzburg/MiddleClick-BigSur#23]
Currently I can run this on Monterey 12.0.1, Apple Silicon. But it is using Intel via Rosetta 2, can we have a ARM build for this app?

**Comment by JosephTico** [comment]
Someone already made a port:

https://github.com/werty1st/MiddleClick-m1

There's a precompiled release there, however you need to manually give the +x permission to the executable inside the app bundle:

````
MiddleClick.app/Contents/MacOS
❯ chmod +x MiddleClick
```
Seems like the only change is a simple bug fix, easy enough for @artginzburg to merge?

**Comment by artginzburg** [comment]
@jackblk could you confirm that the new version works fine? https://github.com/artginzburg/MiddleClick-BigSur/releases/tag/2.5

**Comment by JosephTico** [comment]
The new build is working perfectly for me!

**Comment by jackblk** [comment]
> @jackblk could you confirm that the new version works fine? https://github.com/artginzburg/MiddleClick-BigSur/releases/tag/2.5

Works perfectly for me too, cheers!
