### ISSUE TITLE
Support for Montery 12.0.1?

### ISSUE THREAD

**Issue by Jont828** [artginzburg/MiddleClick-BigSur#24]
Is MiddleClick supported for Montery 12.0.1 on Intel? I installed it but it doesn't seem to be working and the icon randomly disappears and reappears in the menu bar.

**Comment by artginzburg** [comment]
Looks like you need to give it Accessibility permissions in System Preferences > Security & Privacy > Privacy > Accessibility

**Comment by andresmoschini** [comment]
I have the same problem in Big Sur 11.6 Intel:

![2021-11-22_20-01-50 (1)](https://user-images.githubusercontent.com/1157864/142948079-a07c0ba5-2b62-4c09-83c4-c51bd526f488.gif)

<img width="586" alt="image" src="https://user-images.githubusercontent.com/1157864/142948052-56358ff9-3e51-4054-afc5-3a67036c725d.png">

And the permissions seems to be ok:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/1157864/142948198-a46fae86-c828-4f5e-a007-cbe69e109089.png">

Any idea?

**Comment by artginzburg** [comment]
@andresmoschini for now, I suggest to try to completely remove MiddleClick from Accessibility (with "-" button), then add it again. Sounds reasonable because the app continuously reopening means exactly that it can't get access to multitouch data.

I'll try to investigate it later this week, could be possible that something else prevents access to multitouch in Monterey.

**Comment by jackblk** [comment]
I also have this issue, my recommendation is to:

* Close MiddleClick
* Remove MiddleClick in Accessibility
* Restart MacOS
* Open MiddleClick and add it to Accessibility again

If you try to add it back before restarting, it might hang your system and you have to do a hard reset via power button. It happened to me twice already while changing version.

**Comment by andresmoschini** [comment]
Thanks @jackblk and @jackblk!

I followed the steps and it started to work ❤️

**Comment by BioFacLay** [comment]
@jackblk This exact thing happened to me today. I first encountered the problem described by @Jont828 yesterday after using my Macbook with an external (Logitech) mouse for the first time. Before MiddleClick was working flawlessly. Might be a coincidence, though.

I'm happy to provide further information if needed.
