### ISSUE TITLE
MiddleClick can't be opened

### ISSUE THREAD

**Issue by twcostain** [artginzburg/MiddleClick-BigSur#25]
Using latest version (2.5)
"“MiddleClick” can’t be opened because Apple cannot check it for malicious software."

![image](https://user-images.githubusercontent.com/2950905/143242132-97dd23cc-b324-4e3e-9d62-9e2169a76420.png)

Installed using Homebrew.

Am I doing something wrong, or has the notarisation failed somehow?

**Comment by artginzburg** [comment]
There is no notarisation right now. But it is, as always, possible to open MiddleClick by right-clicking on its icon and choosing "Open".

You can also install it with --no-quarantine option to bypass the problem completely.
`brew install --cask --no-quarantine middleclick`

**Comment by twcostain** [comment]
Thanks for the quick response.
Closing because what you said solves the problem.
Do you know when a notarised version might be available?

**Comment by artginzburg** [comment]
@twcostain actually, I don't think a notarised version is worth the money here. Middleclick is an open-source tool.
Of course, if there is any way to notarise apps without paying, we should consider it.

**Comment by twcostain** [comment]
Ah, fair enough 😄. Just wondering how/why 2.4.8.1 was notarised, but 2.5 isn't is all

**Comment by artginzburg** [comment]
2.4.8.1 was notarised in 2020, and promised to be notarised till 2024. But my Apple Developer Program subscription has recently ended, so 2.5 not being notarised seems logical.

**Comment by twcostain** [comment]
Ah, that does make a lot of sense!
Thanks for both answering my questions and maintaining the app.
It's very annoying that this app is even needed in the first place 😝
