### ISSUE TITLE
4 fingers tap

### ISSUE THREAD

**Issue by Wiredframe** [artginzburg/MiddleClick-BigSur#26]
Hey there, would you please consider adding 4 fingers tap and click? This would help to resolve the 3 fingers to move conflict. Thanks :)

**Comment by artginzburg** [comment]
We already have this, I think: https://github.com/artginzburg/MiddleClick-BigSur/blob/main/README.md#number-of-fingers

**Comment by Wiredframe** [comment]
Cool, thanks!
