### ISSUE TITLE
Changes code signature in version 2.5?

### ISSUE THREAD

**Issue by suschizu** [artginzburg/MiddleClick-BigSur#27]
Hello!
I've received a notification that the code signature has changed in that latest download:
`EXPECTED Arthur Ginzburg (R2294BC6J8) but FOUND Apple Development: Arthur Ginzburg (MA8T6SPDN2)`
can you verify it?

**Comment by artginzburg** [comment]
It's managed automatically by Xcode, and my Apple Developer Program subscription has recently ended, so code signature change seems valid here.

**Comment by suschizu** [comment]
ok thanks for the confirmation :)

**Comment by core-code** [comment]
thanks @artginzburg !

> and my Apple Developer Program subscription has recently ended

that explains why the team-id changed (R2294BC6J8 => MA8T6SPDN2) , but not why the signature kind changed from a real one (Developer ID) to a wrong one (Apple Development - just meant for Mac App Store uploads). 

i was under the impression real signatures (Developer ID) were free for everyone for a few years now and just the option to publish on the Mac App Store costs the yearly 100$

**Comment by artginzburg** [comment]
@core-code I should check it out probably. Sounds good.
