### ISSUE TITLE
MacOS 12.5 says this is malware and won't run it

### ISSUE THREAD

**Issue by rooneyp** [artginzburg/MiddleClick-BigSur#44]

**Comment by arndff** [comment]
I'm having the same problem. What I tried is:
- right click on MiddleClick
- Get Info
- Override malware protection

However, that didn't help me either -- when I tried to open the app, it says "The application 'MiddleClick' can't be opened."

Tried to delete it & install it with brew (the preferred way, described in repo's README) -- no success again.

Please, help us fix this somehow, as I can't live without this app, literally...

**Comment by ElectricS01** [comment]
This is also happening on the MacOS Ventura Public Beta 4

**Comment by Gumija** [comment]
Does not work for me either. Is this because of a malware db update or something system specific?
Can someone confirm it not working on a macOS version before 12.5?

**Comment by lawand** [comment]
I tried the usual way to override but it didn't work: Right-click the application, select “Get Info”, and check the “Override Malware Protection” box

**Comment by benonymus** [comment]
Same issue on macOS 12.5.1

**Comment by jasonycw** [comment]
It was working on 12.5.1 last week, but this week after I restart the Mac, it cannot be started.
Tried `Override malware protection`
<img width="372" alt="image" src="https://user-images.githubusercontent.com/4518597/187113457-f27c974f-0f47-46ff-b08e-726be4e4c45d.png">

**Comment by yusufkinatas** [comment]
Same here, my productivity decreased %50 after MacOS update because of this :(

**Comment by arndff** [comment]
> Does not work for me either. Is this because of a malware db update or something system specific? Can someone confirm it not working on a macOS version before 12.5?

@Gumija I updated to 12.5.1 almost instantly; the app was working fine till yesterday...

**Comment by Avivhdr** [comment]
+1

**Comment by Marius30** [comment]
+1

**Comment by Chrobin111** [comment]
When I dig into the contents of the app, try to manually run the executable and then click the question mark on the warning message, the help message says

> The app’s authorization has been revoked

So has the certificate expired?

**Comment by sky-andremartins** [comment]
+1

**Comment by IhorDeyneha** [comment]
I also have the same problem. I couldn’t live without MiddleClick.

**Comment by nathansalaun-sofia** [comment]
I know it's not possible for everyone but cloning the repo + building the app to run locally worked fine for me.

**Comment by davystrong** [comment]
I built it myself and it appears to be working. Just had to remove the code signing (obviously). In my case I left it blank since I don't have a Mac developer account.

**Comment by yusufkinatas** [comment]
It would be a huge step towards increasing everyone's productivity, if someone could release the local built version with working certification on GitHub. So everyone here could easily download & use it instead of spending time building it on their locals. The world would be thankful to such a person. @nathansalaun-sofia @davystrong 😊

**Comment by nathansalaun-sofia** [comment]
I agree however I don't have anything setup to publish a signed app

**Comment by alicangok** [comment]
On my MacOS 12.1, the app seems to start, but doesn't work anymore. And I assume it keeps restarting every few seconds, as the icon disappears and reappears in the menubar.

**Comment by nathansalaun-sofia** [comment]
@alicangok look at the logs in Xcode: the app restarts because it lacks Accessibility permissions. Quit the Xcode version, build it then install it in Applications, then grant it permissions and it will work

**Comment by Filaipus** [comment]
Having the same issue as everyone. Unfortunately don't have a developer account either or I would love to help.

**Comment by BJKle** [comment]
what has changed from yesterday to today, that we have this issue and the app isn't trusted anymore?
I don't even know how to create an app.
Tough luck 👎

**Comment by PetarLotrean** [comment]
@davystrong worked for me, thanks!

**Comment by Gumija** [comment]
if @artginzburg is not around we might need to make a new fork and name it MiddleClick-Monterey xD
A release there could be the correct place to share the new app file.

I am quite new to mac os development, I've been in and out in the last half year in my free time.
But everything I read about code signing is pointing to the direction that if that was the issue we could bypass it by right-click > Open or such. Is this an issue here because of the Accessibility rights? Can that only be accessed by signed code maybe?

**Comment by Reedbeta** [comment]
Having this problem even on macOS 11.6.8. It started after doing a `brew upgrade` that updated MiddleClick 2.4.8.1 to 2.5.

**Comment by s0menickname** [comment]
Have this problem since updating to 12.5.1. Will try to download Xcode and build it myself now

**Comment by DouglasNewhouse** [comment]
> @alicangok look at the logs in Xcode: the app restarts because it lacks Accessibility permissions.

Aha! So it looks like the easiest thing to do in the short term is download the previous version (2.4.8.1), drag that to your Applications folder, override the malware check, then **manually** add MiddleClick's Accessibility permission using the + button. There will already be an entry, but it's for the old version.
This works for me anyway, and it's much easier than installing an entire build environment.

**Comment by alicangok** [comment]
@DouglasNewhouse Does 2.4.8.1 work on M1 machines? The 2.5.0 specifically included M1 fixes.

(For what it's worth, I had been using 2.5.0 without problem on my MacOS 12.1 M1 for months. and it stopped working suddenly today, without any updates to anything)

**Comment by s0menickname** [comment]
Thanks to @davystrong I managed to build it myself in Xcode.

I can start it and it appears in the tray but it doesn't work (like the wheel click doesn't happen) and every 5 seconds the icon disappears and after a second appears again. I also had to download Xcode which takes **22 GB** of space. Too bad, Apple!

M2 MB Air.

**Comment by davystrong** [comment]
@s0menickname did you remove it from your accessibility settings and re add it? That should fix it.
(Yes, Xcode is huge and is also pretty useless)

**Comment by s0menickname** [comment]
> @s0menickname did you remove it from your accessibility settings and re add it? That should fix it.

@davystrong god bless you, that helped!

**Comment by alicangok** [comment]
> Confirmed that stepping back to 2.4.8.1 (from Releases page [here](https://github.com/artginzburg/MiddleClick-BigSur/releases/tag/2.4.8.1)) and removing/re-adding the accessibility setting fixed it for me. BTW, I'm on an M1 Macbook, and this version has always worked for me (presumably through Rosetta rather than native).

Thank you. This solves the issue (through Rosetta translation, which probably comes at a little computational cost)

**Comment by DouglasNewhouse** [comment]
> Does 2.4.8.1 work on M1 machines? The 2.5.0 specifically included M1 fixes  

Yes - at least on my M1 Air.

**Comment by jasonycw** [comment]
Thanks, can confirm 2.4.8.1 is working on M1 Pro

**Comment by arndff** [comment]
I also went with installing 2.4.8.1 instead of building locally the latest version.

Works fine (at least for now).

Thank you all! :)

**Comment by trihutama** [comment]
MiddleClick ver 2.5 Build locally debug mode,
[MiddleClick.zip](https://github.com/artginzburg/MiddleClick-BigSur/files/9450779/MiddleClick.zip)
to open this app, go to finder > right click > then Open

**Comment by crozet-magenta** [comment]
thank you @trihutama it works fine like this

**Comment by IhorDeyneha** [comment]
> > @alicangok look at the logs in Xcode: the app restarts because it lacks Accessibility permissions.
> 
> Aha! So it looks like the easiest thing to do in the short term is download the previous version (2.4.8.1), drag that to your Applications folder, override the malware check, then **manually** add MiddleClick's Accessibility permission using the + button. There will already be an entry, but it's for the old version. This works for me anyway, and it's much easier than installing an entire build environment.

For me this method is working on MacBook pro (Intel). 

Thank you guys! Thank you @DouglasNewhouse

**Comment by willdashwood** [comment]
> For peope who don't have Xcode , [MiddleClick.zip](https://github.com/artginzburg/MiddleClick-BigSur/files/9450779/MiddleClick.zip) this is without certificate to open this app, go to finder > right click > then Open

Thanks @trihutama. I uninstalled view brew first (brew remove middleclick) then removed MiddleClick from Security & Privacy > Accessibility list. Extracted your zip file and copied the app over to Applications folder. Ran:

`sudo xattr -r -d com.apple.quarantine /Applications/MiddleClick.app` 

Then manually added the app back under Security & Privacy > Accessibility list. Works fine now, cheers!

**Comment by rdelassus** [comment]
I've tried both the build the solution and the old version solution, and in both cases I have the same issues : The app is killed every 3 seconds and restarts, and I cannot middle click

**Comment by trihutama** [comment]
> I've tried both the build the solution and the old version solution, and in both cases I have the same issues : The app is killed every 3 seconds and restarts, and I cannot middle click

@rdelassus try delete old apps first using AppCleaner, remove old MiddleClick accessibility option , then open app again with right click > Open

**Comment by sky-andremartins** [comment]
I've tried reinstalling with the previous version (2.4.8.1) and on Mac M1 it keeps restarting

**Comment by artginzburg** [comment]
My understanding is that when I recently signed in to Xcode on a new machine, my old certificate has been revoked (received an email stating this 3 days ago), and a new one was generated, so apps signed prior to that need to be rebuilt.

The fun thing is that it's a development certificate, without notarization. Wonder how much of extra security does that actually bring to users...

Try downloading this: https://github.com/artginzburg/MiddleClick-BigSur/releases/tag/2.5.0.1
It's simply rebuilt with no changes at all. Another funny thing is that the app size just shrank by almost half a kilobyte.

**Comment by hiraken0427** [comment]
GREAT WORK!
You have made my work far more efficient. Thank you very much.

**Comment by SuchSkill** [comment]
@artginzburg would it also be possible to update brew version in a timely manner?

**Comment by rooneyp** [comment]
Much thanks!

**Comment by chrisma** [comment]
Thank you @artginzburg! This is essential macOS software! 🥳
