### ISSUE TITLE
extend bluetooth magic trackpad not working

### ISSUE THREAD

**Issue by lvii** [artginzburg/MiddleClick-BigSur#47]
Hi

After update to `2.5.0.1 — Re-signed` extend bluetooth touchpad could **NOT** working.

macbook pro's touchpad was work.

Thanks

**Comment by artginzburg** [comment]
Could you specify which version works for you? 2.5.0.1 does not include any code changes.

**Comment by artginzburg** [comment]
2.5 and 2.5.0.1 are identical in code, which means that whatever works or doesn't work will persist in both of them (if the app successfully runs in the first place, of course). Looks like magic to me.

Also not sure if I know what's the "extend bluetooth touchpad" feature
