### ISSUE TITLE
Hide/Remove Status Bar Icon 

### ISSUE THREAD

**Issue by pyamo** [artginzburg/MiddleClick-BigSur#49]
Is it possible to create a build of the app that removes the status bar icon, or allow some sort of setting - could be as simple as a text based flag somewhere. I understand there are other apps that can organize status bar icons such as bartender, but middleclick is the only app I typically have open and apps like bartender or hiddenbar add an extra arrow that I also dont need, would be easiest if I could just ditch the icon entirely. 

Thanks!

**Comment by artginzburg** [comment]
https://github.com/artginzburg/MiddleClick-BigSur#hide-status-bar-item
