### ISSUE TITLE
App closes and opens every 3 second

### ISSUE THREAD

**Issue by alexeyinn** [artginzburg/MiddleClick-BigSur#51]
Macbook Pro M2 - Ventura
App just closes and opens every 3 second (i can see in top screen bar), and middle finger click does not works.
I have not this problem with base fork this app - https://github.com/cl3m/MiddleClick

**Comment by artginzburg** [comment]
Have you tried https://github.com/artginzburg/MiddleClick-BigSur#attention-make-sure-to?

**Comment by alexeyinn** [comment]
> Have you tried https://github.com/artginzburg/MiddleClick-BigSur#attention-make-sure-to?

I fully remove old version from mac.

Can you say more about, what i must di in privacy setting? Old version works with out it

**Comment by artginzburg** [comment]
Old version was not updated for a while, so I expect you'd never run into the error with it.

Looks like all you need to do is remove any version of MiddleClick from System Preferences > Security & Privacy > Privacy > Accessibility. As I remember, it is often left hanging there even if the app was deleted.
Then add the new version there (via the Plus button or drag-n-drop), and it should start working.

**Comment by alexeyinn** [comment]
> Old version was not updated for a while, so I expect you'd never run into the error with it.
> 
> Looks like all you need to do is remove any version of MiddleClick from System Preferences > Security & Privacy > Privacy > Accessibility. As I remember, it is often left hanging there even if the app was deleted. Then add the new version there (via the Plus button or drag-n-drop), and it should start working.

Thank you so much it's works for me now
